version: '3'
services:
  # Servicio para la aplicación Node.js
  web:
    build: .  # Construye la imagen usando el Dockerfile
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al puerto 3000 del host
    environment:
      - DATABASE_URL=postgres://postgres:ejemplo@db:5432/reservas_hoteles
    depends_on:
      - db  # Depende del servicio de la base de datos

  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres  # Usa la imagen oficial de PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ejemplo
      POSTGRES_DB: reservas_hoteles
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos

# Volumen para persistir los datos de PostgreSQL
volumes:
  postgres_data: